language: python

python: 3.5
env:
  - TOX_ENV=py35
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=py27

matrix:
  fast_finish: true

install: pip install -r requirements_test.txt

script: tox -e $TOX_ENV
